# Tips For Easier Python and NumPy Code

## Pythonic Code

It is possible to write Java-style and C-style code in Python, but it is usually much easier to write (and read!) Python-style code. Such code is called 'pythonic'.

For example, if you wanted to sum up the squares of the numbers from 1 to 10, you *could* write it like this.

In [1]:
s = 0
i = 1

while i <= 10:
    s += i**2
    i += 1
    
s

385

It works perfectly well, but the while loop can be replaced with a simpler for loop.

In [2]:
s = 0

for i in range(1, 11):
    s += i**2
    
s

385

To decide which type of loop to use, the rules are:
* `for` loops are used when the number of iterations is known,
* `while` are used when the number of iterations isn't known.

The loop can be entirely removed with a "list comprehension". Once we have a list of squares, the `sum` function will automatically add up the list.

In [3]:
squares = [i**2 for i in range(1, 11)]
s = sum(squares)

squares, s

([1, 4, 9, 16, 25, 36, 49, 64, 81, 100], 385)

As a final simplifying step, we can eliminate the intermediate list by turning the list comprehension into a "generator" which is input directly into `sum`.

In [4]:
s = sum(i**2 for i in range(1, 11))

s

385

I hope you agree that this easier to write and read (once you know what everything means).

It's worth noting that Python doesn't even create the intermediate list with the last method! It generates (hence "generator") one value at a time and updates the sum. That doesn't matter in such a small example, but it can make a difference if your program has to work with lists of thousands or millions of values.

## NumPy Arrays

The core feature of NumPy is the array. Arrays differ from Python lists because an array has a fixed length, and usually contains only numbers. NumPy is filled with tools to make working with arrays easy. For example `linspace` creates an array of evenly spaced numbers between two points. For example, an array of 20 numbers from 0 to 10.

In [5]:
import numpy as np

x = np.linspace(0, 5, 10)

x

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

You probably expected the array `[0. 0.5 1. 1.5 2. 2.5 3. 3.5 4. 4.5 5.]`. However, if you count that array you'll find it has 11 numbers in it, not 10.

In [6]:
x = np.linspace(0, 5, 11)

x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

Adding, subtracting, and multiplying arrays works much like with vectors in math.

In [7]:
x * 2

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [8]:
y = np.linspace(10, 20, 11)

x + y

array([ 10. ,  11.5,  13. ,  14.5,  16. ,  17.5,  19. ,  20.5,  22. ,
        23.5,  25. ])

Most NumPy functions work nicely on arrays. Applying a function to an array simply applies the function to each element of the array. For example, NumPy's `power` function computes a power of a number and applying it to a list computes the power of each element.

In [9]:
np.power(x, 2)

array([  0.  ,   0.25,   1.  ,   2.25,   4.  ,   6.25,   9.  ,  12.25,
        16.  ,  20.25,  25.  ])